//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationStructureService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class role : INotifyPropertyChanged
    {
        private int role_id1;
        private string role_name1;

        public int role_id 
        
        { get => role_id1; set 
            {
                role_id1 = value;
                OnPropertyChanged(nameof(role_id));
            } 
        
        }
        public string role_name { 
            
            get => role_name1;


            set

            { 
                role_name1 = value;
                OnPropertyChanged(nameof(role_name));
            }
        
        
        }

        public event PropertyChangedEventHandler PropertyChanged;


        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

    }
}
